# -*- coding: utf-8 -*-
"""Sleep_health_lifestyle_dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PTlSgDoW4aXS6hQSbqdrdHEXQ_bXYtba
"""

"""
# Sleep Health and Lifestyle Dataset - EDA

Ushbu loyihada 374 kishilik "Sleep Health and Lifestyle" dataseti tahlil qilinadi.
Dataset odamlarning kasbi, uyqu davomiyligi, uyqu sifati, stress darajasi, BMI
kategoriyasi va boshqa ko'rsatkichlarini o'z ichiga oladi.

Maqsad - quyidagi savollarga javob topish:
- Uyqu davomiyligi va uyqu sifati o'rtasida qanday bog'liqlik bor?
- Stress darajasi uyqu sifatiga qanday ta'sir qiladi?
- Qaysi kasb egalari eng ko'p/eng kam uxlaydi?
- Datasetda outlier va kuchli korrelyatsiyalar bormi?
"""

!pip install opendatasets

import opendatasets as od

od.download("https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset")

import pandas as pd

df = pd.read_csv("/content/sleep-health-and-lifestyle-dataset/Sleep_health_and_lifestyle_dataset.csv")

df.shape

df.head(10)

df.info()

df.columns

df.isna().sum()

per = (df.isna().sum()/len(df)*100).round(3)
per.sort_values(ascending=False)

"""Natijadan ko'rishimiz mumkinki Sleep Disorder ustuni 58% bo'sh buni biz o'chirib tashlasak ham bo'ladi"""

df2 = df.copy()
df2.drop(columns='Sleep Disorder', inplace=True)

df2.isna().sum()

df2.duplicated().sum()

"""Dataset tozalandi. Bundan buyon barcha tahlillar tozalangan `df2` ustida davom ettiriladi."""

df2.describe()

df2['Gender'].value_counts()
df2['Occupation'].value_counts()

"""Kasb bilan sleep hours ni guruhlab ko'ramiz qaysi kasbdagilar ko'proq yoki kamroq uxlashini solishtiramiz"""

df2.groupby('Occupation')['Sleep Duration'].mean()

import seaborn as sns
import matplotlib.pyplot as plt


# Histplot
fig, axes = plt.subplots(1, 3, figsize=(12, 5))

sns.histplot(data=df2, x='Sleep Duration', ax=axes[0])
axes[0].ticklabel_format(style='plain', axis='y')
axes[0].set_title('Uxlash soati')

sns.histplot(data=df2, x='Quality of Sleep', ax=axes[1], color='#42cef5')
axes[1].ticklabel_format(style='sci', axis='y')
axes[1].set_title('Uyqu sifati')

sns.histplot(data=df2, x='Stress Level', ax=axes[2], color='#f56642')
axes[2].ticklabel_format(style='scientific', axis='y')
axes[2].set_title('Stress darajasi')

plt.tight_layout()
plt.show()

"""Grafiklardan ko'rishimiz mumkinki bizda ma'lumot kamligi tufayli taqsimotlar Normal Distribution emas ya'ni ma'lumotlar Qo'ng'iroq shaklda taqsimlanmagan"""

import matplotlib.pyplot as plt
import seaborn as sns

# Grafik o'lchamini belgilash
plt.figure(figsize=(8, 6))

# Grafikni chizish (y-o'qi bo'yicha)
sns.countplot(data=df2, y='Occupation')

# Sarlavha qo'shish
plt.title('Occupation Count')

# Grafik elementlarini tekislash va ko'rsatish
plt.tight_layout()
plt.show()

"""Datasetimizda Doktor va hamshiralar ma'lumotlar ko'p"""

df2['BMI Category'].value_counts()

# "Normal Weight" qiymatini "Normal" ga o'zgartirish
df2['BMI Category'] = df2['BMI Category'].replace('Normal Weight', 'Normal')

# Natijani qaytadan tekshirish
print(df2['BMI Category'].value_counts())

# Grafik o'lchamini belgilash
plt.figure(figsize=(8, 5))

# Grafikni chizish (x-o'qi bo'yicha va ko'k rangda)
sns.countplot(data=df2, x='BMI Category', color='#42cef5')

# Sarlavha qo'shish
plt.title('BMI Category Count')

# Grafik elementlarini tekislash va ko'rsatish
plt.tight_layout()
plt.show()

# Grafik o'lchamini belgilash
plt.figure(figsize=(6, 5))

# Grafikni chizish (x-o'qi bo'yicha va to'q sariq rangda)
sns.countplot(data=df2, x='Gender', color='#f56642')

# Sarlavha qo'shish
plt.title('Gender Count')

# Grafik elementlarini tekislash va ko'rsatish
plt.tight_layout()
plt.show()

# # # OUTLIERLARNI TEKSHIRISH
fig, ax = plt.subplots(1, 2, figsize=(12, 4))

ax[0].boxplot(df2['Heart Rate'])
ax[0].set_title('Yurak urishi')

ax[1].boxplot(df2['Daily Steps'])
ax[1].set_title('Kunlik qadamlar')
plt.show()

Q1, Q3 = df2['Heart Rate'].quantile([0.25, 0.75])
IQR = Q3 - Q1
outliers = df2[df2['Heart Rate'] > Q3 + 1.5 * IQR]   # 116 ta
print(f'Outlierlar soni: {len(outliers)}')
# outliers2 = df2[df2['Heart Rate'] < Q1 - 1.5 * IQR]   # 0 ta
# outliers2

# # # Korrelyatsiyalarni ko'rib chiqish

num = df2.select_dtypes(include='number').drop(columns=['Person ID'])
cats = df2.select_dtypes(include='object').columns

corr = num.corr()
corr

plt.figure(figsize=(10, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation heatmap')
plt.show()

"""Xullas heatmap dan ko'rinib turibdiki bizda juda ko'p ustunlarda bog'liqlik bor ekan. Ajoyib dataset desak ham bo'ladi. Agar ushbu datasetda "ML Model" qursak uning to'g'rilik ko'rsatgichi yuqori chiqadi chunki ma'lumotlar bir-biriga mantiqiy ravishda bog'langan."""

# # 1. Uyqu sifati va Stress darajasi (Scatter Plot yoki Bar Plot)
plt.figure(figsize=(8, 5))

sns.barplot(data=df2, x='Quality of Sleep', y='Stress Level', palette='coolwarm')
plt.title("Uyqu sifati va Stress darajasi o'rtasidagi bog'liqlik")
plt.xlabel('Uyqu sifati (Quality of Sleep)')
plt.ylabel('Stress darajasi (Stress Level)')
plt.show()

"""Heatmapda ham ko'ringandiki -0.9 korrelyatsiya edi va bu kuchli bog'liqlik. Ya'ni Uyqu sifati qancha yuqori bo'lsa, Stress darajasi shuncha past bo'ladi"""

# # 2. Uyqu davomiyligi va Uyqu sifati (Scatter Plot + Trend chizig'i)
plt.figure(figsize=(10, 7))

sns.regplot(data=df2, x='Sleep Duration', y='Quality of Sleep')
plt.title('Uyqu davomiylig va Uyqu sifati')
plt.xlabel('Uyqu vaqti (Sleep Duration)')
plt.ylabel('Uyqu sifati (Quality of Sleep)')
plt.show()

"""Uyqu vaqti qancha ko'p bo'lsa, uyqu sifati ham shuncha yaxshi bo'ladi"""

# # 3. Kasblar bo'yicha uyqu sifati (Solishtirish uchun)
plt.figure(figsize=(10, 6))
# Har bir kasb uchun o'rtacha uyqu sifatini hisoblab, tartib bilan chizish
sns.barplot(data=df2, y='Occupation', x='Quality of Sleep', errorbar=None, palette='viridis')
plt.title("Kasblar kesimida o'rtacha uyqu sifati")
plt.xlabel("O'rtacha uyqu sifati")
plt.ylabel('Kasb (Occupation)')
plt.tight_layout()
plt.show()

"""Boya ko'rganimizda Sleep Duration eng kami Sales Representive edi (5,9 soat), va eng ko'p Engineer (7.9) edi. Sleep Duration bilan Quality of Sleep bir-biriga 0.88 korrelyatsiyada bog'langan. SHuning uchun bu grafikda ham Engineer larning Uyqu sifati (Quality of Sleep) yaxshi chiqqan, Sales Representive esa aksincha uyqu sifati yomon."""

"""
## Xulosalar (Key Findings)

1. **Uyqu sifati va Stress darajasi kuchli teskari bog'liqlikka ega (corr ~ -0.9)**:
   uyqu sifati qancha yuqori bo'lsa, stress darajasi shuncha past.
2. **Uyqu davomiyligi va uyqu sifati o'rtasida kuchli musbat bog'liqlik bor (corr ~ 0.88)**:
   uyqu qancha uzoq bo'lsa, uyqu sifati ham shuncha yaxshi baholanadi.
3. **Kasb uyqu sifatiga sezilarli ta'sir qiladi**: Engineerlar eng uzoq (~7.9 soat) va
   eng sifatli uyquga ega, Sales Representative'lar esa eng kam (~5.9 soat) va eng past
   sifatli uyquga ega - bu ikki toifa orasidagi farq katta.
4. **Heart Rate ustunida 116 ta outlier aniqlandi** (IQR usuli bilan), Daily Steps'da
   sezilarli outlier topilmadi.
5. **Dataset ustunlari o'zaro mantiqiy bog'langan** (kuchli korrelyatsiyalar mavjud),
   shu sababli bu dataset kelajakda ML model (masalan, Sleep Disorder yoki Quality of
   Sleep'ni bashorat qilish) qurish uchun ham yaxshi asos bo'la oladi.
"""
